version: "3"
services:
  app:
    image: daishun/php:5.6-fpm
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache
    env_file:
      - .env

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app


